# Generated by Django 5.2 on 2025-05-02 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('folder', '文件夹'), ('file', '文件')], max_length=10)),
                ('actual_file', models.FileField(blank=True, null=True, upload_to='get_user_file_path')),
                ('is_compressed', models.BooleanField(default=False)),
                ('compression_algorithm', models.CharField(blank=True, choices=[('zstd', 'Zstandard'), ('gzip', 'GZIP'), ('lz4', 'LZ4')], max_length=20, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('storage_type', models.CharField(choices=[('standard', '标准存储'), ('hive', 'Hive'), ('hbase', 'HBase'), ('cloud', '云端存储')], default='standard', max_length=20)),
                ('storage_path', models.CharField(blank=True, help_text='离线存储系统中的文件路径', max_length=512, null=True)),
                ('storage_key', models.CharField(blank=True, help_text='存储系统中的文件唯一标识', max_length=255, null=True)),
                ('cloud_url', models.URLField(blank=True, help_text='云端存储的文件URL', max_length=512, null=True)),
                ('size', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.file')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_manager.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'parent'], name='file_manage_user_id_54a4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['storage_type'], name='file_manage_storage_8f9e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filetag',
            unique_together={('file', 'tag')},
        ),
    ]
