# Generated by Django 5.2 on 2025-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='path_hash',
            field=models.CharField(default='', editable=False, max_length=32, unique=True),
        ),
    ]
