# Generated by Django 5.2 on 2025-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_file_last_downloaded_file_path_hash'),
        ('tag_manager', '0002_tag_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(related_name='files', through='file_manager.FileTag', to='tag_manager.tag'),
        ),
    ]
