# Generated by Django 5.2 on 2025-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_file_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='compression_ratio',
            field=models.FloatField(blank=True, help_text='压缩率百分比，如65表示65%', null=True),
        ),
    ]
