# Generated by Django 5.2 on 2025-04-30 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1, message='名称不能为空'), django.core.validators.RegexValidator('^[\\w\\u4e00-\\u9fa5]{1,20}$', message='仅允许中英文、数字和下划线')])),
                ('description', models.TextField(blank=True, max_length=200)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='颜色格式必须为#FFFFFF或#FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['-created_at'],
            },
        ),
    ]
