# Generated by Django 5.2 on 2025-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='importance',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1, verbose_name='重要性'),
        ),
    ]
