# Generated by Django 5.2 on 2025-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager', '0002_tag_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='file_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关联文件数'),
        ),
    ]
