# Generated by Django 5.2 on 2025-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='sub_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
