# Generated by Django 5.2 on 2025-05-03 16:36

import compression_manager.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compression_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TempUploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=compression_manager.models.get_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('uploaded', '上传完成'), ('failed', '上传失败')], default='uploading', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compression_manager.compressiontask')),
            ],
            options={
                'db_table': 'temp_uploaded_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
