# Generated by Django 5.2 on 2025-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuploadedfile',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
