[project]
name = "compression-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "blosc>=1.11.2",
    "brotli>=1.1.0",
    "django>=5.2",
    "django-cors-headers>=4.7.0",
    "django-extensions>=4.1",
    "django-filter>=25.1",
    "djangorestframework>=3.16.0",
    "djangorestframework-simplejwt>=5.5.0",
    "langchain>=0.3.25",
    "langchain-community>=0.3.23",
    "langchain-openai>=0.3.16",
    "lxml>=5.4.0",
    "lz4>=4.4.4",
    "openai>=1.77.0",
    "pillow>=11.2.1",
    "py7zr>=0.22.0",
    "pydotplus>=2.0.2",
    "pydub>=0.25.1",
    "python-lzo>=1.15",
    "python-snappy>=0.7.3",
    "requests>=2.32.3",
    "setuptools==80.3.1",
    "zopfli>=0.2.3.post1",
]
